polarismesh/polaris-go

api/consumer.go, api/consumer_impl.go, api/limit.go, api/limit_impl.go, api/provider.go, api/provider_impl.go, examples/quickstart/consumer/main.go, examples/quickstart/provider/main.go
=> feat: add new Api by address

pkg/model/now.go
[issue69](https://github.com/polarismesh/polaris-go/issues/69)
=> [ISSUE #69]bugfix/timeval:fix mac_os bug

pkg/model/now.go, pkg/model/service.go, plugin/statreporter/prometheus/model.go, test/serviceroute/nearbyRouting_suite.go, test/serviceroute/ruleRouting_suite.go, test/stability/server_switch_suite.go, test/testdata/sr_nearby.yaml, test/testdata/sr_rule.yaml, test/testdata/sr_rule_variable.yaml, test/testdata/sr_setdivision.yaml
=> [ISSUE #67]fix prometheus caller info

pkg/model/service.go
=> support fetch all services

go.mod, go.sum, pkg/flow/quota/window.go, pkg/model/pb/rule.go, pkg/model/rule.go, plugin/servicerouter/rulebase/base.go, test/serviceroute/ruleRouting_suite.go
=> feat: 支持Regexp2正则 支持正则反向匹配

LICENSE, benchmark/benchmain/main.go, examples/services/main.go, pkg/model/pb/rule.go, pkg/model/service.go, pkg/plugin/healthcheck/healthcheck.go, plugin/healthcheck/http/http.go, plugin/healthcheck/tcp/tcp.go, plugin/serverconnector/grpc/convert.go, plugin/serverconnector/grpc/operation_async.go, plugin/serverconnector/sidecar/client/client.go, plugin/serverconnector/sidecar/dns/question.go, plugin/statreporter/tencent/monitor/utils.go, test/circuitbreak/healthcheck_suite.go, test/serviceroute/nearbyRouting_suite.go, test/serviceroute/ruleRouting_suite.go, test/serviceroute/setdivision_router_suite.go, test/stability/cache_update_fast_suite.go, test/subscribe/subscribe_suit.go
=> License update and group imports

.github/workflows/testing.yml, .golangci.yml, pkg/algorithm/hash/base.go, pkg/clock/clock.go, pkg/flow/async_flow.go, pkg/flow/quota/assist.go, pkg/flow/quota/window_async.go, pkg/log/log.go, pkg/model/pb/assist.go, pkg/model/util.go, pkg/plugin/ratelimiter/model.go, plugin/ratelimiter/reject/bucket_qps.go, plugin/ratelimiter/unirate/bucket_leaky.go, revive.toml, test/serviceroute/dstmetaRouting_suite.go, test/serviceroute/setdivision_router_suite.go
=> fix golangci

examples/quickstart/provider/main.go, pkg/model/service.go, plugin/serverconnector/common/convert.go
=> 注册实例时支持指定实例id

examples/quickstart/provider/main.go, pkg/flow/watch_flow.go, polaris.yaml
=> fix:修复实例watch被异常唤醒问题

examples/configuration/encrypt/polaris.yaml, examples/quickstart/provider/main.go, examples/watch/service/longpull/main.go, examples/watch/service/longpull/polaris.yaml, pkg/flow/watch_flow.go, pkg/model/pb/service.go, pkg/model/service.go
=> fix:修复服务监听丢失事件&nil panic问题

examples/quickstart/provider/main.go, pkg/config/api.go, pkg/config/config_file.go, pkg/config/location_provider.go, pkg/flow/configuration/config_flow.go, pkg/flow/configuration/file_repo.go, pkg/flow/configuration/local_cache.go, pkg/flow/impl.go, pkg/model/util.go, pkg/plugin/configconnector/config_file.go, plugin/configconnector/polaris/config_connector.go, plugin/configfilter/crypto/crypto.go, polaris.yaml
=> Fix issue 171 & 172

examples/circuitbreaker/instance/README.md, examples/circuitbreaker/instance/consumer/go.sum, examples/circuitbreaker/instance/consumer/main.go, examples/circuitbreaker/instance/provider/go.sum, pkg/model/circuitbreaker.go, pkg/model/local/value.go, plugin/circuitbreaker/composite/counter.go, plugin/circuitbreaker/composite/task_pool.go
=> fix: fix 熔断器 panic

api/config.go, examples/configuration/crud/go.sum, examples/configuration/normal/go.mod, examples/configuration/normal/go.sum, examples/configuration/normal/polaris.yaml, examples/quickstart/consumer/Dockerfile, examples/quickstart/consumer/go.mod, examples/quickstart/consumer/go.sum, examples/quickstart/consumer/polaris.yaml, examples/quickstart/k8s/configmap-consumer.yaml, examples/quickstart/k8s/configmap-provider.yaml, examples/quickstart/k8s/deployment-consumer.yaml, examples/quickstart/k8s/deployment-provider.yaml, examples/quickstart/provider/Dockerfile, examples/quickstart/provider/go.mod, examples/quickstart/provider/go.sum, examples/quickstart/provider/isolate.sh, examples/quickstart/provider/main.go, examples/quickstart/provider/polaris.yaml, pkg/config/api.go, pkg/config/default.go, pkg/config/impl.go, pkg/flow/configuration/config_flow.go, pkg/flow/configuration/file_repo.go, pkg/model/context.go, pkg/plugin/loadbalancer/proxy.go, pkg/version/version.go, plugin/configconnector/polaris/config_connector.go
=> feat:support user custom sdk labels

examples/quickstart/provider/main.go, plugin/configconnector/polaris/config_connector.go, plugin/serverconnector/grpc/operation_async.go, plugin/serverconnector/grpc/operation_sync.go
=> fix:修复配置中心客户端鉴权接口设置

plugin/servicerouter/rulebase/base.go
Fixes #
https://github.com/polarismesh/polaris-go/issues/213
此问题在main中已修复，因为main代码一些go interface已变，trpc适配工作较大，所以在v1.5.x上打补丁
@chuntaojun @ArmstrongCN @linfengchen
模块：naming，serviceRouter
=> fix:v1.5.x parameter类型路由规则，同步main上修改，rawMetaValue matchAll

pkg/flow/circuitbreaker_flow.go
=> fix decorator

plugin/loadbalancer/common/half_open.go, plugin/loadbalancer/hash/hash.go, plugin/loadbalancer/maglev/maglev.go, plugin/loadbalancer/ringhash/ringhash.go
=> loadbalancer: fix redundant code

.gitignore, examples/circuitbreaker/instance/README.md, examples/circuitbreaker/service/README.md
=> rm unused file

pkg/flow/quota/remote.go
=> 修复分布式限流场景下rpc连接泄漏的问题

pkg/flow/configuration/file_repo.go
=> fix:文件配置持久化字段添加非空判断
